name: in_app_update_prompt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # runs the CI every first day of every month at 00:00 AM
    - cron: "0 0 1 * *"

jobs:
  dart:
    runs-on: ubuntu-latest

    strategy:
      matrix:        
        channel:
          - stable
          # - beta

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      # It is executed separatly
      - name: Removing example folder
        run: rm -rf example       

      - name: Install dependencies
        run: flutter pub get

      - name: Check format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze .

      - name: Run tests
        run: flutter test -j 1 --no-pub --coverage --test-randomize-ordering-seed random

      - name: Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 60
          path: coverage/lcov.info

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

